### ISSUE TITLE
Automating builds

### ISSUE THREAD

**Issue by seanhawkridge** [emoriarty/jekyll-notion#90]
Hi! Thanks for all your hard work on this jekyll-notion. I saw in one of your blog posts you mention a process for automating builds. When you have a moment could you give me some pointers for how you approach this? Thanks!

**Comment by emoriarty** [comment]
Hello @seanhawkridge 👋 !
I use Gitlab to build my website with Jekyill but the gist is the same for Github. Right below you can have a look a what the setup looks like in Gitlab CI/CD.

```yaml
image: ruby:2.7.8

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install bundler:2.1.4
  - bundle config set deployment 'true'
  - bundle install
  - bundle exec jekyll clean

test:
  stage: test
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/bundle
  script:
    - bundle exec jekyll build -d test
  artifacts:
    expire_in: 1 week
    paths:
      - test
  except:
    - master

pages:
  stage: deploy
  cache:
    - key:
        files:
          - Gemfile.lock
      paths:
        - vendor/bundle
  script:
    - bundle exec jekyll build --config _config.yml,_config.prod.yml -d public
  artifacts:
    paths:
      - public
  only:
    - master

```
You can do the same with Github actions, which is [documented](https://jekyllrb.com/docs/continuous-integration/github-actions/) in the Jekyll docs pages.
Once you're able to run Jekyll in your CI/CD, you must set the Notion secret token in an environment variable in the CI/CD settings so jekyll-notion is able to download the Notion pages. You can read about Github actions secrets [here](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions).
