### ISSUE TITLE
potential incompatibility with jekyll-archives

### ISSUE THREAD

**Issue by anteromontonio** [emoriarty/jekyll-notion#95]
I follow [these instructions](https://enrq.me/dev/2022/03/24/managing-jekyll-posts-in-notion/) to manage posts from notion.
I am also using jekyll-archives to manage the blog, the code associated with the configuration of the blog is the following:

``` jekyll
blog_name: Grab a cup?  # blog_name will be displayed in your blog page
blog_description: My personal (not-necessary-academic) blog.
permalink: /blog/:year/:title/
```

while the part corresponding to jekyll-archives is as follows:

```jekyll
jekyll-archives:
  enabled: [year, tags,] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    # category: archive-category
  permalinks:
    year: '/blog/:year/'
    tag: '/blog/tag/:name/'
    # category: "/blog/category/:name/"
```

When building the site of a blog imported from notion with title Post, the following directory 2024/post is created under /blog.\
Observe that I don't mean a directory named 2024 and another directory named post under the later (as expected) but a directory with the name '2024/post' under blog. As a consequence the yearly archive is broken (also the tags archives are broken).

The archives worked perfectly if the posts are cheated manually (and not through an import from notion), that is the reason why I am raising the issue here.

Thanks in advace.

**Comment by emoriarty** [comment]
Hello @anteromontonio.

I've tested with my own site the issue you mention and did not see any problem at all. The jekyll-archives seems to fit pretty well. The following tree directory is a build with a similar configuration to yours. Note the `index.html` pages in each year directory are the archive pages.

```bash
├── _site
│   ├── about.html
│   ├── assets
│   │   ├── img
│   │   │   └── circleci-lifecycle.png
│   │   ├── style.css
│   │   └── style.css.map
│   ├── blog
│   │   ├── 2019
│   │   │   ├── beyond-merge.html
│   │   │   └── index.html
│   │   ├── 2020
│   │   │   ├── blocks-js-rb-py.html
│   │   │   ├── circleci-basics.html
│   │   │   ├── confinement-films.html
│   │   │   ├── cra-path-aliases.html
│   │   │   ├── de-pelis-de-ahora.html
│   │   │   ├── hoisting-in-monorepos.html
│   │   │   ├── index.html
│   │   │   └── jekyll-101-for-authors.html
│   │   ├── 2021
│   │   │   ├── cypress-parallel-in-circleci.html
│   │   │   ├── index.html
│   │   │   ├── intercept-requests-with-cypress.html
│   │   │   ├── locate-method-definition-file-ruby.html
│   │   │   └── using-different-bundler-versions.html
│   │   ├── 2022
│   │   │   ├── index.html
│   │   │   ├── jekyll-notion.html
│   │   │   ├── load-notion-pages-in-jekyll.html
│   │   │   ├── managing-jekyll-posts-in-notion.html
│   │   │   ├── notion_to_md.html
│   │   │   └── the-story-of-react.html
│   │   ├── 2023
│   │   │   ├── embedding-videos-with-jekyll-notion.html
│   │   │   ├── index.html
│   │   │   ├── migrate-from-delayedjob-to-goodjob.html
│   │   │   └── taming-administrate-a-gentle-monkey-patch.html
│   │   └── 2024
│   │       ├── index.html
│   │       └── websockets-in-kubernetes.html
```

The configuration looks as follows.

```yaml
notion:
  databases:
    - id: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      filter: { "property": "done", "checkbox": { "equals": true } }
      sorts: [{ "timestamp": "created_time", "direction": "descending" }]
    - id: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      collection: gists
    - id: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      data: stuff
  pages:
    - id: XXXXXXXXXXXXXXXXXXXXXXXXXXXX

jekyll-archives:
  enabled: ['year']
  layout: archive
  permalinks:
     year: '/blog/:year/'

permalink: /blog/:year/:title
```
I'm not sure what the problem is, but I'm not able to repeat it.
Have you tried to build the site it without the permalink option? Perhaps with you give more details like the OS, Ruby, and libraries version I'd be able to figure it out what happens.

**Comment by anteromontonio** [comment]
The behaviour is quite strange. 

I made a silly mistake and misinterpreted my tree directory. The problem is not a naming problem. It seems to me that jekyll-archives is not aware of the posts imported via notion-jekyill. 

Again, here are extracts of my _config file:

Notion:

```yaml
# -----------------------------------------------------------------------------
# Notion
# -----------------------------------------------------------------------------
notion:
  # fetch_mode: true #notion-fetch
  databases:
    - id: XXXXXXXXXXXXXXXXXX
      collection: posts
      filter: { "property": "status", "select": { "equals": "published" } }
    - id: XXXXXXXXXXXXXXXXXX
      collection: pages
    - id: XXXXXXXXXXXXXXXXXX
      collection: news
    - id: XXXXXXXXXXXXXXXXXX
      data: talks

```
 Archives

```yaml
# -----------------------------------------------------------------------------
# Jekyll Archives
# -----------------------------------------------------------------------------

jekyll-archives:
  enabled: [year, tags] # enables year, tag and category archives (remove if you need to disable one of them).
  layouts:
    year: archive-year
    tag: archive-tag
    # category: archive-category
  permalinks:
    year: "/blog/:year/"
    tag: "/blog/tag/:name/"
#     # category: "/blog/category/:name/"
```

And the resulting tree directory (with a few comments on the files):


```
blog
├── 2024
│   ├── index.html. <------------ 2024 has an index.html that only shows the 2 posts 
                                   created without notion
│   ├── photo-gallery <--- Created without notion
│   │   └── index.html
│   ├── test <--- Created without notion
│   │   └── index.html
│   └── welcome-to-my-blog <--- Created witgh notion (not shown in the 2024 archive)
│       └── index.html
├── 2025 <------------ 2025 has no index.html; the only 2025 post was created with notion.
│   └── hay-que-llevarla-leve-con-la-banda
│       └── index.html
├── index.html
└── tag <------------ Similar behaviour than with the years, tags appearing in posts created without 
                      Notion have their archive page, which only shows posts containing such tags
                      that were created without notion. Tags appearing only in Notion-created posts 
                      have no archive.
    ├── formatting
    │   └── index.html
    ├── images
    │   └── index.html
    └── test
        └── index.html
```

Here is the (relevant) output on building, I cannot avoid noticing that Jekyll Archives is executed before Jekyll Notion.


```
 Generating: JekyllJupyterNotebook::Generator finished in 0.000265 seconds.
        Generating: Jekyll::Archives::Archives finished in 0.001134 seconds.
           Reading: _posts/2024-12-30-hay-que-llevarla-leve-con-la-banda.md
     Jekyll Notion: Page => Hay que llevarla leve con la banda
                    URL => /blog/2025/hay-que-llevarla-leve-con-la-banda/
                    Props => ["draft", "categories", "date", "status", "featured", "tags", "layout", "id", "title", "created_time", "cover", "icon", "last_edited_time", "archived", "created_by_object", "created_by_id", "last_edited_by_object", "last_edited_by_id", "slug", "ext", "excerpt"]
           Reading: _posts/2024-12-30-welcome-to-my-blog.md
     Jekyll Notion: Page => Welcome to my blog
                    URL => /blog/2024/welcome-to-my-blog/
                    Props => ["draft", "categories", "date", "status", "featured", "tags", "layout", "id", "title", "created_time", "cover", "icon", "last_edited_time", "archived", "created_by_object", "created_by_id", "last_edited_by_object", "last_edited_by_id", "slug", "ext", "excerpt"]
```

The website is being build in MacOs using Jekyll Version: 4.3.4 and Ruby 3.1.3. The same behaviour is obtained when building on github pages. 

[https://anteromontonio.github.io/blog/](https://anteromontonio.github.io/blog/)
