### ISSUE TITLE
NoMethodError: undefined method 'inject' for nil:NilClass in notion_to_md/page.rb:16:in 'title' during build

### ISSUE THREAD

**Issue by wu-hongjun** [emoriarty/jekyll-notion#96]
**Environment:**

*   `jekyll-notion` version: 2.4.3 
*   `notion_to_md` version: 2.4.1 
*   Ruby version: 3.1.0 
*   Operating System: macOS (darwin 24.4.0)

**Description:**

When running `jekyll build` or `jekyll serve`, the process fails with the following error:

```
<path_to_gem>/notion_to_md-2.4.1/lib/notion_to_md/page.rb:16:in `title': undefined method `inject' for nil:NilClass (NoMethodError)
	from <path_to_gem>/jekyll-notion-2.4.3/lib/jekyll-notion/generators/collection_generator.rb:54:in `block in generate_pages'
  # ... potentially more stack trace lines ...
```

This error occurs during the `CollectionGenerator` phase, specifically when trying to process the title of a page fetched from Notion via the `notion_to_md` dependency.

**Configuration (`_config.yml`):**

```yaml
notion:
  databases:
    - id: "1c2b<REDACTED>b5c0"
      collection: posts
      filter: { "property": "Published", "checkbox": { "equals": true } }
      sorts: [{ "timestamp": "created_time", "direction": "descending" }]
      properties:
        title: "Title"
        date: "Date"
        tags: "Tags"
        author: "Author"
        image: "Cover" # Note: Mapped from 'Cover' in config, but API showed 'Cover Image' property name? Might be unrelated.
        layout: "post"
        published: "Published"
```

**Troubleshooting Steps Performed:**

1.  **Confirmed API Access:** Verified the `NOTION_TOKEN` is correct and allows API access.
2.  **Checked for Empty Titles:** Queried the Notion database API for pages where `Published` is `true` AND `Title` is empty. This query returned **zero** results.
3.  **Checked Specific Page Data:** Queried the Notion API for the specific page ("Test Post") being processed. The API response showed the page data, including the `Title` property structure, appears valid and conforms to the expected Notion API format (an array containing rich text objects).
    ```json
    // Example structure from API for the single published page
    "Title": {
      "id": "title",
      "type": "title",
      "title": [
        {
          "type": "text",
          "text": { "content": "Test Post", "link": null },
          "annotations": { /* ... */ },
          "plain_text": "Test Post",
          "href": null
        }
      ]
    }
    ```
4.  **Checked All Published Pages:** Queried the Notion API for *all* pages where `Published` is `true`. This query returned only **one** page ("Test Post"), confirming only this page should be processed based on the filter.
5.  **Cleared Cache:** Deleted the `.jekyll-cache` directory; the error persisted.
6.  **Disabled Plugin:** Commenting out `jekyll-notion` in the `plugins` list and the entire `notion:` block in `_config.yml` allows the Jekyll build to complete successfully, confirming the issue originates within this plugin.

**Hypothesis:**

Given that only one page is being processed, its data appears valid according to the Notion API, and there are no published pages with empty titles, this suggests a potential bug within `jekyll-notion` or `notion_to_md`. The plugin might be incorrectly handling the title data structure received from the API, even when it appears valid, leading to `nil` being passed to the `.inject` method.
